Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60   # 请求超时控制，60s
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads   #最终保存目录
  UploadServerUrl: http://127.0.0.1:8000/static   # 用于展示的文件服务地址
  UploadImageMaxSize: 5 #允许的最大空间大小(MB)
  UploadImageAllowExts:  # 允许的文件后缀
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root
  Password: chnvideo2012
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: eddycjy     # 令牌密钥(不可暴露到外部，这里是指演示，可以放到环境变量中让程序去读)
  Issuer: blog-service  # 签发者
  Expire: 7200   # 有效时间 7200s
Email:
  Host: smtp.qq.com
  Port: 465   # 不要使用25端口，在一些云服务器上25端口会被禁掉
  UserName: xxxx@qq.com
  Password: xxxxxx
  IsSSL: true
  From: xxxx@qq.com
  To:
    - 1xxx@qq.com
    - 2xxx@qq.com